src/components/footer/footer.css, src/components/header/header.css, src/pages/home/home.css, src/style.css
Hey @torch2424!  My first PR here aims to increase the white spacing on the app, aiming to improve readability of the content and make it tad easier on the eyes :) Obviously this is subjective so totally understand if you prefer it how it is, so let me know if want me to change anything/revert anything back. 
Looking forward to contributing more going forward!
**master**
**PR**
=> Increase white space on the home screen

package-lock.json, package.json, src/pages/project/project.js, src/preact.config.js
Using the Preact CLI Plugin: https://github.com/developit/preact-cli-plugin-async
=> Fixed Deployment / CI Issues

package.json, src/pages/project/project.js
Fix from debugging in #3 :joy:
=> Forgot to save from the last PR :(

package-lock.json, package.json, src/preact.config.js, src/sw.js
Since we upgraded our preact cli, the asses are not automatically upgraded anymore :cry: So Added a service worker for that, and got things working offline for the list :smile:
=> Added a custom service worker

src/pages/about/about.js, src/style.css
closes #1 
Simply creates all the copy for the about page, and gives all the relevant credits :smile:
=> Created the about page

package.json
=> Added step to move _redirects to correct directory

showcase/UnoPlatform
Added new project - Uno Platform
=> Create Uno Platform

showcase/fastq-bio.md
This PR is to fix Issue #14 regarding the Figma description. I also updated the body description, let me know what you think!
=> Issue 14 - Fix the Figma description + edits to the main description

showcase/rust-fern-bench.md, showcase/webm-mp4-encoder.md
I would like to add my recent Wasm related projects!
=> Add webm-mp4-encoder and rust-fern-bench

showcase/gdevelop.md
I updated the description of GDevelop, fixed a reference to Google Earth and added some links :)
Thanks for this nice website!
=> Improve GDevelop description

README.md, showcase/js-wasm_performance_comparison.md, showcase/porous_absorber_calculator.md
Contributing two new WASM apps
=> Additions from Chris W

showcase/UnoPlatform.md, src/components/header/header.css, src/pages/about/about.js, src/pages/home/home.css, src/style.css
closes #26 
closes #18 
closes #13
=> Fixed all the small issues for the website

showcase/redis.md
See https://medium.com/fluence-network/porting-redis-to-webassembly-with-clang-wasi-af99b264ca8
=> Added redis port from Fluence Labs

showcase/pprmnt.md
Hi! Just sharing my own little Web Assembly based application. Hope that's okay.
Let me know if you have any feedback on the submission -- should I include more info about the tech used, more context, etc.
Thanks for the great resource btw 💪
=> feat: add pprmnt.cc to showcase

showcase/micrio.md
Recently switched to stable client lib running on AssemblyScript.. :)
=> added Micrio showcase

showcase/atmo.md
This adds an entry for Suborbital Atmo, the framework for building function-based cloud applications.
=> added showcase entry for Atmo

showcase/wasmcloud.md
Would love to showcase `wasmCloud` on this project!
=> Added wasmcloud to the project list

showcase/sql-practice, showcase/sql-practice.md
sql-practice is a practical example of implementing sql.js on a website.
I am not a professional at using git so I'm sorry if I made a mistake when submitting this.
I noticed it gives a "unknown date" for the date added field. I don't know if there's something I had to do to fix this or it will just work when its hosted.
=> Added sql-practice.com as an example.

showcase/kubewarden.md
Add an entry for the [Kubewarden](https://www.kubewarden.io/) project
=> Add Kubewarden to showcase

src/pages/about/about.js
Hello @torch2424!
First of all, thanks for creating this amazing list, it's very helpful.
So I was checking this website a while a go to find some cool projects that make use of WebAssembly and noticed some typos in the About page, so I thought about sending a PR to fix them :)
=> Fix typos in About page

showcase/fractal_wasm.md
Added a link to a detailed tutorial showing how this app was written
=> Add blog link

showcase/pdfstandalone.md
Please add CIB pdf standalone, which processes all offered PDF usecases in webassembly
=> added pdf standalone

showcase/chromium-ink.md
Hi. I'm the TLM of the Ink project.
I've started receiving emails from folks who, having seen our project mentioned on this site, erroneously assume that it's an open-source project.
=> Correct Ink verbiage.

showcase/tarmac.md
Adding a simple showcase entry for Tarmac: https://github.com/madflojo/tarmac
=> Adding Tarmac Showcase

showcase/opencascadejs.md
Great website, thanks a lot for building an maintaining it!
With this PR, I would like to add `OpenCascade.js` - a port of the OpenCascade CAD library that can be used via WebAssembly.
=> Add OpenCascade.js
